apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prepper-frontend.fullname" . }}-nginx
  labels:
    {{- include "prepper-frontend.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        sub_filter '<base href="/" />' '<base href="{{ .Values.basePath | default "/" | trimSuffix "/" }}/">';
        sub_filter_once on;

        location = /sw.js {
            add_header Cache-Control "no-store, no-cache, must-revalidate";
            try_files $uri =404;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass {{ .Values.backend.url }}/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
